# Generated by Django 3.2.16 on 2022-11-18 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entryggg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('seasonround', models.IntegerField()),
                ('tournamentweek', models.IntegerField()),
                ('gameone', models.IntegerField()),
                ('gametwo', models.IntegerField()),
                ('gamethree', models.IntegerField()),
                ('gamefour', models.IntegerField()),
                ('gamefive', models.IntegerField()),
                ('gwpoints', models.IntegerField()),
                ('gwspeedscore', models.IntegerField()),
                ('totalpoints', models.IntegerField()),
                ('totalspeedscore', models.IntegerField()),
                ('position', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
